version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - run: echo $PWD
      - checkout
      - python/install-deps
      - run: pytest --verbose --junit-xml test-reports/results.xml

workflows:
  version: 2.1
  "Test":
    jobs:
      - build