version: 2.1

jobs:
  test:
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - restore_cache: 
          key: v10-dependencies-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            conda create -p=cenv python=2.7 -y
            echo "source activate ./cenv" >> $BASH_ENV
            source activate ./cenv
            conda install --file requirements.txt
      - save_cache:
          key: v10-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "cenv"
      - run: python -m pytest --ignore=cenv --verbose --junit-xml test-reports/results.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2.1
  "Test":
    jobs:
      - test
