version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: pytest --verbose --junit-xml test-reports/results.xml
      - store_test_results:
          path: test-reports

workflows:
  version: 2.1
  "Test":
    jobs:
      - build
      - test:
          requires:
            - build