version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: 
          command: |
            sudo chmod -R 777 /usr/local/lib/python2.7/site-packages
            sudo chown -R circleci /usr/local/lib/python2.7/site-packages
      - restore_cache: 
          key: v6-dependencies-{{ checksum "requirements.txt" }}
      - run: pip install --user -r requirements.txt
      - save_cache:
          key: v6-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/bin"
      - run: python -m pytest --verbose --junit-xml test-reports/results.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2.1
  "Test":
    jobs:
      - test